#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0
"""Check phase for xnec2c.

Upstream's `make check` only verifies that the examples listed in Makefile.am
match the files on disk; it runs no simulation and takes no measurable time.
The real material for a test is already in the tarball though: examples/ holds
worked antenna models and examples/data/ holds the CSV that upstream's own
update-example-data.sh produced for each one. This runs a subset of those models
headless and compares the numbers against the committed reference.

Each row of the CSV is one frequency step with impedance, VSWR, S11, gains and
front-to-back ratio, so a comparison exercises the whole pipeline: geometry
parsing, the interaction matrix, the solve, and the field and gain post
processing on top of it.
"""

import csv
import math
import pathlib
import subprocess
import sys

# Models to run, chosen to stay quick while covering different kinds of
# structure: free space and over ground, wire and helix, single element and
# array, with and without a meaningful front-to-back ratio.
MODELS = [
    # Free space wire structures.
    "2m_yagi",
    "2m_extended_yagi",
    "15m_delta-loop",
    "2m_sqr_halo",
    "gray_hoverman",
    # Over a ground plane, including one Sommerfeld-Norton solution and one
    # model with a cliff, which drive the SOMNEC path.
    "40m-moxon",
    "80m_zepp",
    "1MHz_tower",
    "T12m-H24m",
    "20-40m_vert_sommerfeld_cliff",
    # Helices and arcs, which exercise the GA/GH geometry cards.
    "23cm_helix+screen",
    "137Mhz-QFHA3",
    # Transmission lines and networks between elements.
    "35-55MHz_logper",
    # Larger wire-grid structures.
    "airplane",
    "20m_car_ant",
    "satellite",
]

# Columns compared, with the tolerance each is held to.
#
# Only the directly computed quantities are compared. The reference CSVs were
# generated by upstream on a different compiler and possibly a different linear
# algebra backend, and this build additionally runs with -O3 -fcx-fortran-rules
# -fno-signed-zeros, so exact equality is not on offer and would be a false
# promise. The tolerances below are far tighter than any real regression would
# survive.
#
# s11_ang, zphase and fb_ratio are deliberately left out. They are angles and
# ratios derived from quantities that pass through zero, so a relative
# tolerance on them is meaningless: a few parts per million on the underlying
# complex number can swing a phase by degrees or a front-to-back null by dB.
# The quantities they are derived from are compared instead.
#
# gain_viewer and gain_viewer_net are left out for a different reason: they are
# not properties of the antenna at all. measurements.c computes them as
# Viewer_Gain(structure_proj_params, ...), the gain in whichever direction the
# structure view happens to be pointing, and those angles come from the saved
# GUI state. Headless they take their default value, which is not the
# orientation upstream had on screen when the reference data was generated, so
# they differ by design rather than through any numerical error.
#
# gain_max_theta and gain_max_phi are also skipped: they report the direction
# of peak gain, which for a pattern with a broad or symmetric maximum can jump
# between equivalent lobes without the gain itself changing.
# The tolerance is 1e-7 relative on every computed column. Measured deviation
# from the reference across these models is between 1e-13 and 3e-11, so that is
# several thousand times the observed spread. It is deliberately not tightened
# to the observed figure: OpenBLAS selects its kernels from the CPU it finds at
# runtime, so the exact arithmetic differs between machines, and a bound set
# from one host's results would fail on another for no good reason. Any real
# regression is orders of magnitude larger than this.
COMPARED = {
    "mhz": 1e-9,
    "zreal": 1e-7,
    "zimag": 1e-7,
    "zmag": 1e-7,
    "vswr": 1e-7,
    "s11": 1e-7,
    "gain_max": 1e-7,
    "gain_net": 1e-7,
}


def close(got, want, rtol):
    if math.isnan(got) and math.isnan(want):
        return True
    # An absolute floor, so columns that legitimately pass through zero are not
    # held to a relative tolerance against nothing.
    return abs(got - want) <= rtol * max(abs(want), 1.0)


def compare(produced, reference, model):
    with produced.open() as f:
        got = list(csv.DictReader(f))
    with reference.open() as f:
        want = list(csv.DictReader(f))

    if not want:
        sys.exit(f"check: reference {reference} is empty")
    if len(got) != len(want):
        sys.exit(
            f"check: {model}: produced {len(got)} frequency steps, "
            f"reference has {len(want)}"
        )

    missing = sorted(set(COMPARED) - set(want[0]))
    if missing:
        sys.exit(f"check: {model}: reference CSV has no column(s) {missing}")

    worst = (0.0, None)
    for step, (g, w) in enumerate(zip(got, want)):
        for column, rtol in COMPARED.items():
            gv, wv = float(g[column]), float(w[column])
            if not close(gv, wv, rtol):
                sys.exit(
                    f"check: {model}: {column} at step {step} "
                    f"({w['mhz']} MHz) is {gv!r}, reference {wv!r}"
                )
            if not (math.isnan(gv) or math.isnan(wv)):
                rel = abs(gv - wv) / max(abs(wv), 1.0)
                if rel > worst[0]:
                    worst = (rel, column)
    return len(want), worst


def main():
    xnec2c, exampledir, workdir, jobs = sys.argv[1:5]
    exampledir = pathlib.Path(exampledir)
    workdir = pathlib.Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    mathlib_seen = False
    mathlib_line = ""
    for model in MODELS:
        deck = exampledir / f"{model}.nec"
        reference = exampledir / "data" / f"{model}.csv"
        if not deck.is_file():
            sys.exit(f"check: {deck} is missing; update MODELS")
        if not reference.is_file():
            sys.exit(f"check: {reference} is missing; update MODELS")

        produced = workdir / f"{model}.csv"
        # -v is needed for the mathlib report below: pr_info() and pr_notice()
        # are silent at the default verbosity, so without it there is no way to
        # observe which solver was selected.
        proc = subprocess.run(
            [xnec2c, "-v", "-j", jobs,
             "--write-csv", str(produced), "--batch", str(deck)],
            capture_output=True,
            text=True,
        )
        log = proc.stdout + proc.stderr
        if proc.returncode != 0:
            sys.exit(f"check: {model}: xnec2c exited {proc.returncode}\n{log}")

        if not produced.is_file():
            sys.exit(f"check: {model}: xnec2c wrote no CSV\n{log}")
        for line in log.splitlines():
            if "loaded" in line and "OpenBLAS" in line:
                mathlib_seen = True
                mathlib_line = line.strip()

        steps, (rel, column) = compare(produced, reference, model)
        print(f"  {model}: {steps} steps match (worst {rel:.2e} on {column})")

    # The accelerated solver is a runtime dlopen(), so a package can declare the
    # dependency and still ship something that silently falls back to the slow
    # built-in path. Fail if it did not actually load, rather than assume it.
    if not mathlib_seen:
        sys.exit(
            "check: xnec2c never loaded OpenBLAS. mathlib.c dlopen()s it by "
            "soname at startup, so this means the rundep is not actually "
            "satisfiable as declared."
        )
    print(f"xnec2c: all models match the reference data; mathlib: {mathlib_line}")


if __name__ == "__main__":
    main()
